//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace envioVentas2.EnvioVen {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCambio", Namespace="http://schemas.datacontract.org/2004/07/FR.Core.EDM.DTO")]
    [System.SerializableAttribute()]
    public partial class TipoCambio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cve_tipo_cambioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_altaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_finalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_inicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal tipo_cambioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cve_tipo_cambio {
            get {
                return this.cve_tipo_cambioField;
            }
            set {
                if ((this.cve_tipo_cambioField.Equals(value) != true)) {
                    this.cve_tipo_cambioField = value;
                    this.RaisePropertyChanged("cve_tipo_cambio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_alta {
            get {
                return this.fecha_altaField;
            }
            set {
                if ((this.fecha_altaField.Equals(value) != true)) {
                    this.fecha_altaField = value;
                    this.RaisePropertyChanged("fecha_alta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_final {
            get {
                return this.fecha_finalField;
            }
            set {
                if ((this.fecha_finalField.Equals(value) != true)) {
                    this.fecha_finalField = value;
                    this.RaisePropertyChanged("fecha_final");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_inicio {
            get {
                return this.fecha_inicioField;
            }
            set {
                if ((this.fecha_inicioField.Equals(value) != true)) {
                    this.fecha_inicioField = value;
                    this.RaisePropertyChanged("fecha_inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_modificacion {
            get {
                return this.fecha_modificacionField;
            }
            set {
                if ((this.fecha_modificacionField.Equals(value) != true)) {
                    this.fecha_modificacionField = value;
                    this.RaisePropertyChanged("fecha_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal tipo_cambio {
            get {
                return this.tipo_cambioField;
            }
            set {
                if ((this.tipo_cambioField.Equals(value) != true)) {
                    this.tipo_cambioField = value;
                    this.RaisePropertyChanged("tipo_cambio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TResultOfboolean", Namespace="http://schemas.datacontract.org/2004/07/FR.Core.EDM")]
    [System.SerializableAttribute()]
    public partial class TResultOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Productos", Namespace="http://schemas.datacontract.org/2004/07/FR.Core.EDM.DTO")]
    [System.SerializableAttribute()]
    public partial class Productos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionCortaComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionLargaComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GrupoMarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PalabrasClaveComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aplica_cdsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aplica_laboratorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cantidad_medida1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cantidad_medida2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int categoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clasificacion_abc_ldmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigo_barraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigo_produccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string compra_ventaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cuadro_inmedicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cve_producto_satField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cve_unidad_satField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_altaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int generoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int marcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mercancia_consignaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string otorga_descuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal porc_comision_pago_tarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string precio_oficialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int segmentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int subcategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sustancia_activaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipo_cenefaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_compra_prodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int uni_cambio_presentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unidad_medida1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unidad_medida2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCortaComercial {
            get {
                return this.DescripcionCortaComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionCortaComercialField, value) != true)) {
                    this.DescripcionCortaComercialField = value;
                    this.RaisePropertyChanged("DescripcionCortaComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionLargaComercial {
            get {
                return this.DescripcionLargaComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionLargaComercialField, value) != true)) {
                    this.DescripcionLargaComercialField = value;
                    this.RaisePropertyChanged("DescripcionLargaComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GrupoMarca {
            get {
                return this.GrupoMarcaField;
            }
            set {
                if ((this.GrupoMarcaField.Equals(value) != true)) {
                    this.GrupoMarcaField = value;
                    this.RaisePropertyChanged("GrupoMarca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial {
            get {
                return this.NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComercialField, value) != true)) {
                    this.NombreComercialField = value;
                    this.RaisePropertyChanged("NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PalabrasClaveComercial {
            get {
                return this.PalabrasClaveComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.PalabrasClaveComercialField, value) != true)) {
                    this.PalabrasClaveComercialField = value;
                    this.RaisePropertyChanged("PalabrasClaveComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aplica_cdso {
            get {
                return this.aplica_cdsoField;
            }
            set {
                if ((object.ReferenceEquals(this.aplica_cdsoField, value) != true)) {
                    this.aplica_cdsoField = value;
                    this.RaisePropertyChanged("aplica_cdso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aplica_laboratorio {
            get {
                return this.aplica_laboratorioField;
            }
            set {
                if ((object.ReferenceEquals(this.aplica_laboratorioField, value) != true)) {
                    this.aplica_laboratorioField = value;
                    this.RaisePropertyChanged("aplica_laboratorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cantidad_medida1 {
            get {
                return this.cantidad_medida1Field;
            }
            set {
                if ((object.ReferenceEquals(this.cantidad_medida1Field, value) != true)) {
                    this.cantidad_medida1Field = value;
                    this.RaisePropertyChanged("cantidad_medida1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cantidad_medida2 {
            get {
                return this.cantidad_medida2Field;
            }
            set {
                if ((object.ReferenceEquals(this.cantidad_medida2Field, value) != true)) {
                    this.cantidad_medida2Field = value;
                    this.RaisePropertyChanged("cantidad_medida2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int categoria {
            get {
                return this.categoriaField;
            }
            set {
                if ((this.categoriaField.Equals(value) != true)) {
                    this.categoriaField = value;
                    this.RaisePropertyChanged("categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clasificacion_abc_ldm {
            get {
                return this.clasificacion_abc_ldmField;
            }
            set {
                if ((object.ReferenceEquals(this.clasificacion_abc_ldmField, value) != true)) {
                    this.clasificacion_abc_ldmField = value;
                    this.RaisePropertyChanged("clasificacion_abc_ldm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo_barra {
            get {
                return this.codigo_barraField;
            }
            set {
                if ((object.ReferenceEquals(this.codigo_barraField, value) != true)) {
                    this.codigo_barraField = value;
                    this.RaisePropertyChanged("codigo_barra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo_produccion {
            get {
                return this.codigo_produccionField;
            }
            set {
                if ((object.ReferenceEquals(this.codigo_produccionField, value) != true)) {
                    this.codigo_produccionField = value;
                    this.RaisePropertyChanged("codigo_produccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string compra_venta {
            get {
                return this.compra_ventaField;
            }
            set {
                if ((object.ReferenceEquals(this.compra_ventaField, value) != true)) {
                    this.compra_ventaField = value;
                    this.RaisePropertyChanged("compra_venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuadro_inmedica {
            get {
                return this.cuadro_inmedicaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuadro_inmedicaField, value) != true)) {
                    this.cuadro_inmedicaField = value;
                    this.RaisePropertyChanged("cuadro_inmedica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cve_producto_sat {
            get {
                return this.cve_producto_satField;
            }
            set {
                if ((object.ReferenceEquals(this.cve_producto_satField, value) != true)) {
                    this.cve_producto_satField = value;
                    this.RaisePropertyChanged("cve_producto_sat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cve_unidad_sat {
            get {
                return this.cve_unidad_satField;
            }
            set {
                if ((object.ReferenceEquals(this.cve_unidad_satField, value) != true)) {
                    this.cve_unidad_satField = value;
                    this.RaisePropertyChanged("cve_unidad_sat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_alta {
            get {
                return this.fecha_altaField;
            }
            set {
                if ((this.fecha_altaField.Equals(value) != true)) {
                    this.fecha_altaField = value;
                    this.RaisePropertyChanged("fecha_alta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int genero {
            get {
                return this.generoField;
            }
            set {
                if ((this.generoField.Equals(value) != true)) {
                    this.generoField = value;
                    this.RaisePropertyChanged("genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int marca {
            get {
                return this.marcaField;
            }
            set {
                if ((this.marcaField.Equals(value) != true)) {
                    this.marcaField = value;
                    this.RaisePropertyChanged("marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mercancia_consigna {
            get {
                return this.mercancia_consignaField;
            }
            set {
                if ((object.ReferenceEquals(this.mercancia_consignaField, value) != true)) {
                    this.mercancia_consignaField = value;
                    this.RaisePropertyChanged("mercancia_consigna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string otorga_descuento {
            get {
                return this.otorga_descuentoField;
            }
            set {
                if ((object.ReferenceEquals(this.otorga_descuentoField, value) != true)) {
                    this.otorga_descuentoField = value;
                    this.RaisePropertyChanged("otorga_descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal porc_comision_pago_tarjeta {
            get {
                return this.porc_comision_pago_tarjetaField;
            }
            set {
                if ((this.porc_comision_pago_tarjetaField.Equals(value) != true)) {
                    this.porc_comision_pago_tarjetaField = value;
                    this.RaisePropertyChanged("porc_comision_pago_tarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string precio_oficial {
            get {
                return this.precio_oficialField;
            }
            set {
                if ((object.ReferenceEquals(this.precio_oficialField, value) != true)) {
                    this.precio_oficialField = value;
                    this.RaisePropertyChanged("precio_oficial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int segmento {
            get {
                return this.segmentoField;
            }
            set {
                if ((this.segmentoField.Equals(value) != true)) {
                    this.segmentoField = value;
                    this.RaisePropertyChanged("segmento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int subcategoria {
            get {
                return this.subcategoriaField;
            }
            set {
                if ((this.subcategoriaField.Equals(value) != true)) {
                    this.subcategoriaField = value;
                    this.RaisePropertyChanged("subcategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sustancia_activa {
            get {
                return this.sustancia_activaField;
            }
            set {
                if ((this.sustancia_activaField.Equals(value) != true)) {
                    this.sustancia_activaField = value;
                    this.RaisePropertyChanged("sustancia_activa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipo_cenefa {
            get {
                return this.tipo_cenefaField;
            }
            set {
                if ((this.tipo_cenefaField.Equals(value) != true)) {
                    this.tipo_cenefaField = value;
                    this.RaisePropertyChanged("tipo_cenefa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_compra_prod {
            get {
                return this.tipo_compra_prodField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_compra_prodField, value) != true)) {
                    this.tipo_compra_prodField = value;
                    this.RaisePropertyChanged("tipo_compra_prod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_producto {
            get {
                return this.tipo_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_productoField, value) != true)) {
                    this.tipo_productoField = value;
                    this.RaisePropertyChanged("tipo_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uni_cambio_presenta {
            get {
                return this.uni_cambio_presentaField;
            }
            set {
                if ((this.uni_cambio_presentaField.Equals(value) != true)) {
                    this.uni_cambio_presentaField = value;
                    this.RaisePropertyChanged("uni_cambio_presenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unidad_medida1 {
            get {
                return this.unidad_medida1Field;
            }
            set {
                if ((object.ReferenceEquals(this.unidad_medida1Field, value) != true)) {
                    this.unidad_medida1Field = value;
                    this.RaisePropertyChanged("unidad_medida1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unidad_medida2 {
            get {
                return this.unidad_medida2Field;
            }
            set {
                if ((object.ReferenceEquals(this.unidad_medida2Field, value) != true)) {
                    this.unidad_medida2Field = value;
                    this.RaisePropertyChanged("unidad_medida2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categorias", Namespace="http://schemas.datacontract.org/2004/07/FR.Core.EDM.DTO")]
    [System.SerializableAttribute()]
    public partial class Categorias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Tipo_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int categoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_altaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int segmentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int subcategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo_Registro {
            get {
                return this.Tipo_RegistroField;
            }
            set {
                if ((this.Tipo_RegistroField.Equals(value) != true)) {
                    this.Tipo_RegistroField = value;
                    this.RaisePropertyChanged("Tipo_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int categoria {
            get {
                return this.categoriaField;
            }
            set {
                if ((this.categoriaField.Equals(value) != true)) {
                    this.categoriaField = value;
                    this.RaisePropertyChanged("categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_alta {
            get {
                return this.fecha_altaField;
            }
            set {
                if ((this.fecha_altaField.Equals(value) != true)) {
                    this.fecha_altaField = value;
                    this.RaisePropertyChanged("fecha_alta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int segmento {
            get {
                return this.segmentoField;
            }
            set {
                if ((this.segmentoField.Equals(value) != true)) {
                    this.segmentoField = value;
                    this.RaisePropertyChanged("segmento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int subcategoria {
            get {
                return this.subcategoriaField;
            }
            set {
                if ((this.subcategoriaField.Equals(value) != true)) {
                    this.subcategoriaField = value;
                    this.RaisePropertyChanged("subcategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnvioVen.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertarTipoCambio", ReplyAction="http://tempuri.org/IService/InsertarTipoCambioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(envioVentas2.EnvioVen.TipoCambio), Action="http://tempuri.org/IService/InsertarTipoCambioTipoCambioFault", Name="TipoCambio", Namespace="http://schemas.datacontract.org/2004/07/FR.Core.EDM.DTO")]
        envioVentas2.EnvioVen.TResultOfboolean InsertarTipoCambio(envioVentas2.EnvioVen.TipoCambio tipoCambio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertarTipoCambio", ReplyAction="http://tempuri.org/IService/InsertarTipoCambioResponse")]
        System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> InsertarTipoCambioAsync(envioVentas2.EnvioVen.TipoCambio tipoCambio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SyncVentas", ReplyAction="http://tempuri.org/IService/SyncVentasResponse")]
        envioVentas2.EnvioVen.TResultOfboolean SyncVentas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SyncVentas", ReplyAction="http://tempuri.org/IService/SyncVentasResponse")]
        System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> SyncVentasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SyncRetiros", ReplyAction="http://tempuri.org/IService/SyncRetirosResponse")]
        envioVentas2.EnvioVen.TResultOfboolean SyncRetiros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SyncRetiros", ReplyAction="http://tempuri.org/IService/SyncRetirosResponse")]
        System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> SyncRetirosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegisterSustanciasActivas", ReplyAction="http://tempuri.org/IService/RegisterSustanciasActivasResponse")]
        envioVentas2.EnvioVen.TResultOfboolean RegisterSustanciasActivas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegisterSustanciasActivas", ReplyAction="http://tempuri.org/IService/RegisterSustanciasActivasResponse")]
        System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> RegisterSustanciasActivasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegisterProductos", ReplyAction="http://tempuri.org/IService/RegisterProductosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(envioVentas2.EnvioVen.Productos), Action="http://tempuri.org/IService/RegisterProductosProductosFault", Name="Productos", Namespace="http://schemas.datacontract.org/2004/07/FR.Core.EDM.DTO")]
        envioVentas2.EnvioVen.TResultOfboolean RegisterProductos(envioVentas2.EnvioVen.Productos productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegisterProductos", ReplyAction="http://tempuri.org/IService/RegisterProductosResponse")]
        System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> RegisterProductosAsync(envioVentas2.EnvioVen.Productos productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegisterCategorias", ReplyAction="http://tempuri.org/IService/RegisterCategoriasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(envioVentas2.EnvioVen.Categorias), Action="http://tempuri.org/IService/RegisterCategoriasCategoriasFault", Name="Categorias", Namespace="http://schemas.datacontract.org/2004/07/FR.Core.EDM.DTO")]
        envioVentas2.EnvioVen.TResultOfboolean RegisterCategorias(envioVentas2.EnvioVen.Categorias categorias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegisterCategorias", ReplyAction="http://tempuri.org/IService/RegisterCategoriasResponse")]
        System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> RegisterCategoriasAsync(envioVentas2.EnvioVen.Categorias categorias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegisterTipoClientes", ReplyAction="http://tempuri.org/IService/RegisterTipoClientesResponse")]
        envioVentas2.EnvioVen.TResultOfboolean RegisterTipoClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegisterTipoClientes", ReplyAction="http://tempuri.org/IService/RegisterTipoClientesResponse")]
        System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> RegisterTipoClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegisterConceptosCancelacion", ReplyAction="http://tempuri.org/IService/RegisterConceptosCancelacionResponse")]
        envioVentas2.EnvioVen.TResultOfboolean RegisterConceptosCancelacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegisterConceptosCancelacion", ReplyAction="http://tempuri.org/IService/RegisterConceptosCancelacionResponse")]
        System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> RegisterConceptosCancelacionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : envioVentas2.EnvioVen.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<envioVentas2.EnvioVen.IService>, envioVentas2.EnvioVen.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public envioVentas2.EnvioVen.TResultOfboolean InsertarTipoCambio(envioVentas2.EnvioVen.TipoCambio tipoCambio) {
            return base.Channel.InsertarTipoCambio(tipoCambio);
        }
        
        public System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> InsertarTipoCambioAsync(envioVentas2.EnvioVen.TipoCambio tipoCambio) {
            return base.Channel.InsertarTipoCambioAsync(tipoCambio);
        }
        
        public envioVentas2.EnvioVen.TResultOfboolean SyncVentas() {
            return base.Channel.SyncVentas();
        }
        
        public System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> SyncVentasAsync() {
            return base.Channel.SyncVentasAsync();
        }
        
        public envioVentas2.EnvioVen.TResultOfboolean SyncRetiros() {
            return base.Channel.SyncRetiros();
        }
        
        public System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> SyncRetirosAsync() {
            return base.Channel.SyncRetirosAsync();
        }
        
        public envioVentas2.EnvioVen.TResultOfboolean RegisterSustanciasActivas() {
            return base.Channel.RegisterSustanciasActivas();
        }
        
        public System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> RegisterSustanciasActivasAsync() {
            return base.Channel.RegisterSustanciasActivasAsync();
        }
        
        public envioVentas2.EnvioVen.TResultOfboolean RegisterProductos(envioVentas2.EnvioVen.Productos productos) {
            return base.Channel.RegisterProductos(productos);
        }
        
        public System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> RegisterProductosAsync(envioVentas2.EnvioVen.Productos productos) {
            return base.Channel.RegisterProductosAsync(productos);
        }
        
        public envioVentas2.EnvioVen.TResultOfboolean RegisterCategorias(envioVentas2.EnvioVen.Categorias categorias) {
            return base.Channel.RegisterCategorias(categorias);
        }
        
        public System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> RegisterCategoriasAsync(envioVentas2.EnvioVen.Categorias categorias) {
            return base.Channel.RegisterCategoriasAsync(categorias);
        }
        
        public envioVentas2.EnvioVen.TResultOfboolean RegisterTipoClientes() {
            return base.Channel.RegisterTipoClientes();
        }
        
        public System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> RegisterTipoClientesAsync() {
            return base.Channel.RegisterTipoClientesAsync();
        }
        
        public envioVentas2.EnvioVen.TResultOfboolean RegisterConceptosCancelacion() {
            return base.Channel.RegisterConceptosCancelacion();
        }
        
        public System.Threading.Tasks.Task<envioVentas2.EnvioVen.TResultOfboolean> RegisterConceptosCancelacionAsync() {
            return base.Channel.RegisterConceptosCancelacionAsync();
        }
    }
}
